[2025-04-23T07:01:16.405+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T07:01:16.413+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:00:00+00:00 [queued]>
[2025-04-23T07:01:16.416+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:00:00+00:00 [queued]>
[2025-04-23T07:01:16.416+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T07:01:16.421+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): create_tables> on 2025-04-23 07:00:00+00:00
[2025-04-23T07:01:16.427+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=12676) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T07:01:16.427+0000] {standard_task_runner.py:72} INFO - Started process 12678 to run task
[2025-04-23T07:01:16.428+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data', 'create_tables', 'scheduled__2025-04-23T07:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/el_30min.py', '--cfg-path', '/tmp/tmp3f0pspc5']
[2025-04-23T07:01:16.429+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask create_tables
[2025-04-23T07:01:16.447+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:00:00+00:00 [running]> on host eb276ba0497d
[2025-04-23T07:01:16.484+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T07:00:00+00:00'
[2025-04-23T07:01:16.485+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T07:01:16.490+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T07:01:16.492+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T07:01:16.497+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T07:01:16.497+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data, task_id=create_tables, run_id=scheduled__2025-04-23T07:00:00+00:00, execution_date=20250423T070000, start_date=20250423T070116, end_date=20250423T070116
[2025-04-23T07:01:16.520+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T07:01:16.534+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T07:01:16.534+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-23T07:30:00.542+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T07:30:00.551+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:00:00+00:00 [queued]>
[2025-04-23T07:30:00.555+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:00:00+00:00 [queued]>
[2025-04-23T07:30:00.555+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T07:30:00.561+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): create_tables> on 2025-04-23 07:00:00+00:00
[2025-04-23T07:30:00.567+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=16027) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T07:30:00.568+0000] {standard_task_runner.py:72} INFO - Started process 16029 to run task
[2025-04-23T07:30:00.569+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data', 'create_tables', 'scheduled__2025-04-23T07:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/el_30min.py', '--cfg-path', '/tmp/tmpjom0pgv2']
[2025-04-23T07:30:00.570+0000] {standard_task_runner.py:105} INFO - Job 168: Subtask create_tables
[2025-04-23T07:30:00.592+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:00:00+00:00 [running]> on host eb276ba0497d
[2025-04-23T07:30:00.632+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T07:00:00+00:00'
[2025-04-23T07:30:00.633+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T07:30:00.638+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T07:30:00.641+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T07:30:00.646+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T07:30:00.646+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data, task_id=create_tables, run_id=scheduled__2025-04-23T07:00:00+00:00, execution_date=20250423T070000, start_date=20250423T073000, end_date=20250423T073000
[2025-04-23T07:30:00.701+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T07:30:00.715+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T07:30:00.716+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
