[2025-04-23T10:04:26.621+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T10:04:26.630+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data_daily.load_backfill_data_2025-04-20 scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T10:04:26.634+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data_daily.load_backfill_data_2025-04-20 scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T10:04:26.634+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T10:04:26.640+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_backfill_data_2025-04-20> on 2025-04-22 00:00:00+00:00
[2025-04-23T10:04:26.646+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8942) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T10:04:26.647+0000] {standard_task_runner.py:72} INFO - Started process 8944 to run task
[2025-04-23T10:04:26.647+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data_daily', 'load_backfill_data_2025-04-20', 'scheduled__2025-04-22T00:00:00+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/el_daily.py', '--cfg-path', '/tmp/tmpux93b_8j']
[2025-04-23T10:04:26.648+0000] {standard_task_runner.py:105} INFO - Job 285: Subtask load_backfill_data_2025-04-20
[2025-04-23T10:04:26.672+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data_daily.load_backfill_data_2025-04-20 scheduled__2025-04-22T00:00:00+00:00 [running]> on host eb276ba0497d
[2025-04-23T10:04:26.761+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data_daily' AIRFLOW_CTX_TASK_ID='load_backfill_data_2025-04-20' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T00:00:00+00:00'
[2025-04-23T10:04:26.762+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T10:04:26.776+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T10:04:26.781+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T10:04:26.781+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data_daily, task_id=load_backfill_data_2025-04-20, run_id=scheduled__2025-04-22T00:00:00+00:00, execution_date=20250422T000000, start_date=20250423T100426, end_date=20250423T100426
[2025-04-23T10:04:26.820+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T10:04:26.834+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T10:04:26.835+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
