[2025-04-23T07:17:02.769+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T07:17:02.777+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data.load_to_postgres scheduled__2025-04-23T07:16:00+00:00 [queued]>
[2025-04-23T07:17:02.781+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data.load_to_postgres scheduled__2025-04-23T07:16:00+00:00 [queued]>
[2025-04-23T07:17:02.781+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T07:17:02.786+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_to_postgres> on 2025-04-23 07:16:00+00:00
[2025-04-23T07:17:02.793+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14564) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T07:17:02.793+0000] {standard_task_runner.py:72} INFO - Started process 14566 to run task
[2025-04-23T07:17:02.794+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data', 'load_to_postgres', 'scheduled__2025-04-23T07:16:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/el_30min.py', '--cfg-path', '/tmp/tmpibf6nyqf']
[2025-04-23T07:17:02.795+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask load_to_postgres
[2025-04-23T07:17:02.817+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data.load_to_postgres scheduled__2025-04-23T07:16:00+00:00 [running]> on host eb276ba0497d
[2025-04-23T07:17:02.896+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T07:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T07:16:00+00:00'
[2025-04-23T07:17:02.897+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T07:17:02.902+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T07:17:02.906+0000] {el_30min.py:206} INFO - Weather data with air quality loaded successfully into PostgreSQL
[2025-04-23T07:17:02.906+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T07:17:02.910+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T07:17:02.910+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data, task_id=load_to_postgres, run_id=scheduled__2025-04-23T07:16:00+00:00, execution_date=20250423T071600, start_date=20250423T071702, end_date=20250423T071702
[2025-04-23T07:17:02.966+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T07:17:02.975+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T07:17:02.975+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
